### ISSUE TITLE
Add basic information

### ISSUE THREAD

**Issue by itpropro** [Wesmania/dspbp#1]
Thanks for making the work with blueprints a little easier, but it would be appreciated, if you could add some basic information on how to use the tool. It provides no meaningful error messages, often just runs without doing anything but also not exiting and there is not a single example on how to actually dump a blueprint.
There are also no tests or meaningful comments in the source code, so that external people are not really able to understand and thereby use it.

**Comment by Wesmania** [comment]
Hi,

I do admit I mostly made this for my own use, and I haven't been playing DSP recently so it got a bit stale. It probably doesn't parse the new 4-slot planetary stations correctly for example. I'll be happy to work on it some more. Do you have an example for the "runs without doing anything" thing?

**Comment by Wesmania** [comment]
I added a couple better error messages and some examples in README. Let me know what else is needed.

**Comment by Wesmania** [comment]
As for tests, I'm just lazy and can't be bothered to make ingame blueprints for testing :(

**Comment by itpropro** [comment]
> As for tests, I'm just lazy and can't be bothered to make ingame blueprints for testing :(

Thanks a lot for the quick additions! I just mentioned the test as they are one of the few ways that make unnerstanding the code a lot easier. Now that we have some additional information in the README, it would just make sense to potentially make your life as a coder easier (after some painsome hours of writing them :D).
