### ISSUE TITLE
method `write_to` not found in `BlueprintData`

### ISSUE THREAD

**Issue by lxthyme** [Wesmania/dspbp#2]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/8361463/220535735-d3ef605e-dcbb-484c-b242-8f1de0d61942.png">

**Comment by Wesmania** [comment]
Yup, being lazy and not specifying versions in Cargo.toml did that to me. I'll fix that.

**Comment by Wesmania** [comment]
Fixed. Make sure to `cargo clean` and remove your local `Cargo.lock`. Also note that I haven't updated this for a while, since I'm not playing DSP for some time, I'll make some issues.

**Comment by lxthyme** [comment]
@Wesmania Great, thank you!
